version: "3.9"

services:
  sovereign-core-psc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sovereign-core-psc
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash -c "make release"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      - GRADLE_OPTS=-Xmx1024m
    tty: true
